### ISSUE TITLE
Multiple instantiations / benchmarking instantiation times

### ISSUE THREAD

**Issue by jlb6740** [bytecodealliance/lucet#101]
Hi,

I was reading the blog announcement (https://www.fastly.com/blog/announcing-lucet-fastly-native-webassembly-compiler-runtime) that mentioned the instantiation times for wasm modules was under 50 microseconds. This is referring to a single instance of lucet runtime being able to load and instantiate a wasm module in 50 microseconds? I was wondering then how to have multiple instances of a wasm module running to duplicate this. Do you have any pointers here? I am running using the docker script.

**Comment by acfoltzer** [comment]
Hey, these are good questions!
 
> This is referring to a single instance of lucet runtime being able to load and instantiate a wasm module in 50 microseconds?

That's right, though the startup time is not impacted the use of multiple instances. We'll be sharing more detailed performance numbers soon that will break this down.

None of the command-line tools like `lucet-wasi` currently create multiple instances, but we should probably come up with some examples that do.

In the meantime, if you're interested in using the libraries directly, note that we have on `MmapRegion`:

```rust
/// Create a new `MmapRegion` that can support a given number instances, each subject to the
/// same runtime limits.
///
/// The region is returned in an `Arc`, because any instances created from it carry a reference
/// back to the region.
pub fn create(instance_capacity: usize, limits: &Limits) -> Result<Arc<Self>, Error>;
```

Most of our current examples just pass `1` for `instance_capacity`, but you can set a much higher capacity if you'd like. Then, since this method returns an `Arc<MmapRegion>`, you can directly use it in multi-threaded code.

Similarly, `DlModule::load()` also returns an `Arc<DlModule>`, so loaded modules can also be accessed from multiple threads. 

Bringing it all together, on the `Region` trait (which `MmapRegion` implements), we have:

```rust
fn new_instance(&self, module: Arc<dyn Module>) -> Result<InstanceHandle, Error>;
```

Using the region and module from the methods above, you can then create as many new instances as you have capacity for in the region.

Hope this is helpful!

**Comment by jlb6740** [comment]
@acfoltzer 
I just ran across this issue again and realized I never did close this from a while back. FYI I found the comment helpful and still compatible with the API today. An example code snipped I used for anyone else interested: 

```
        let dl_module = DlModule::load("hello.so").unwrap();
        let region = MmapRegion::create(10, &Limits::default()).unwrap();


        let threads: Vec<_> = (0..10).map(|i| {
            let dl_module = dl_module.clone();
            let mut instance = region.new_instance(dl_module).unwrap();
            let wasi_ctx = WasiCtxBuilder::new()
                    .and_then(|x| x.inherit_stdio())
                    .and_then(|x| x.build())
                    .unwrap();
            instance.insert_embed_ctx(wasi_ctx);
            thread::spawn(move || {
                println!("starting({:?})", i);
                instance.run("_start", &[]).unwrap();
            })
            }).collect();

        for t in threads {
	        t.join();
        }

```
