### ISSUE TITLE
Signatures don't need to change size

### ISSUE THREAD

**Issue by awortman-fastly** [bytecodealliance/lucet#349]
This isn't a bug but I'm liable to forget to do this so I'm writing it down:

The [`module_signature`](https://github.com/fastly/lucet/blob/0ad737c16c9d0cb54d12237503d6605eb674de09/lucet-module/src/module_data.rs#L48) we store in `ModuleData` is typed as a `Vec<u8>`, but the signature itself is a constant size we know ahead of time. The signature could instead be `[u8; BYTES]`, which has the upside of never being an incorrect size.

I was initially more concerned when re-reading this because we do some shenanigans to [patch in a signature](https://github.com/fastly/lucet/blob/0ad737c16c9d0cb54d12237503d6605eb674de09/lucet-module/src/module_data.rs#L116-L128) but we go through serde's deserializer, avoiding issues like building a Vec from a raw pointer into some other data. Making this an array would placate the part of my brain prone to reading code incorrectly. :grin:

**Comment by data-pup** [comment]
I tried this out, but I do not think it's doable at the moment. If we flip `module_signature` to be of the type `minisign::SignatureBones::BYTES` we will see a rather unfortunate series of error messages, _this_ one being the most important:

```
[Running 'cargo check']
    Checking lucet-module v0.4.1 (/home/katelyn/lucet/lucet-module)
error[E0277]: arrays only have std trait implementations for lengths 0..=32
  --> lucet-module/src/module_data.rs:36:5
   |
36 |     module_signature: [u8; SignatureBones::BYTES],
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::array::LengthAtMost32` is not implemented for `[u8; 74]`
```

This error stems from this detail mentioned in [the array primitive docs](https://doc.rust-lang.org/std/primitive.array.html):

> This limitation on the size N exists because Rust does not yet support code that is generic over the size of an array type. [Foo; 3] and [Bar; 3] are instances of same generic type [T; 3], but [Foo; 3] and [Foo; 5] are entirely different types. As a stopgap, trait implementations are statically generated up to size 32.

Various tracking issues for const generics are open, but I think having these impls is still a ways off. Until then, I'm not entirely sure finding a workaround would be worth the complexity, since as you noted, we're going through serde's deserializer?
